"""
Report Export Utility
======================
Generates tactical flood risk reports in text and JSON format.

Usage:
    python scripts/export_report.py --village wayanad_meppadi --rainfall 200
"""

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import VILLAGES
from src.flood_model import FloodSimulationModel

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)


def generate_text_report(village_id, rainfall_mm, simulation_result):
    """Generate a tactical text report matching the dashboard format."""
    village = VILLAGES[village_id]
    peak_ts = list(simulation_result["time_steps"].values())[-1]
    stats = peak_ts["stats"]

    lines = [
        "═" * 65,
        "                    JAL DRISHTI FLOOD RISK REPORT",
        "═" * 65,
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Location: {village['name']}, {village['district']}, {village['state']}",
        f"Terrain Type: {village['terrain_type']}",
        "",
        "─── SIMULATION PARAMETERS " + "─" * 39,
        f"Rainfall Input: {rainfall_mm} mm",
        f"Grid Resolution: {simulation_result['metadata']['grid_resolution_m']}m",
        f"Time Steps: {len(simulation_result['time_steps'])}",
        "",
        "─── FLOOD ANALYSIS " + "─" * 45,
        f"Max Water Depth: {stats['max_depth_m']:.1f} m",
        f"Mean Water Depth: {stats['mean_depth_m']:.1f} m",
        f"Cells Flooded: {stats['cells_flooded']}",
        f"Extreme Risk Cells: {stats['cells_extreme']}",
        f"High Risk Cells: {stats['cells_high']}",
        "",
        "─── COVERAGE AREA " + "─" * 46,
        f"Population: {village['population']:,}",
        f"Bounding Box: {village['bbox']}",
        "",
        "═" * 65,
        "            Report generated by Jal Drishti v1.0",
        "═" * 65,
    ]
    return "\n".join(lines)


def export_report(village_id, rainfall_mm, output_dir):
    """Generate and save report for a village."""
    village = VILLAGES.get(village_id)
    if not village:
        logger.error(f"Unknown village: {village_id}")
        return

    logger.info(f"Generating report for {village['name']}: {rainfall_mm}mm rainfall")

    model = FloodSimulationModel(grid_resolution=100, time_steps=7)
    result = model.simulate(
        terrain_type=village["terrain_type"],
        bbox=tuple(village["bbox"]),
        rainfall_mm=rainfall_mm,
    )

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Text report
    text_report = generate_text_report(village_id, rainfall_mm, result)
    text_file = output_path / f"JalDrishti_Report_{village_id}_{datetime.now().strftime('%Y%m%d')}.txt"
    with open(text_file, "w") as f:
        f.write(text_report)
    logger.info(f"Text report saved: {text_file}")

    # JSON report
    json_report = {
        "village_id": village_id,
        "village_name": village["name"],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "rainfall_mm": rainfall_mm,
        "summary": {
            "max_depth_m": result["time_steps"][list(result["time_steps"].keys())[-1]]["stats"]["max_depth_m"],
            "cells_extreme": result["time_steps"][list(result["time_steps"].keys())[-1]]["stats"]["cells_extreme"],
            "cells_flooded": result["time_steps"][list(result["time_steps"].keys())[-1]]["stats"]["cells_flooded"],
        },
    }
    json_file = output_path / f"JalDrishti_Report_{village_id}_{datetime.now().strftime('%Y%m%d')}.json"
    with open(json_file, "w") as f:
        json.dump(json_report, f, indent=2)
    logger.info(f"JSON report saved: {json_file}")

    print(f"\n{text_report}")


def main():
    parser = argparse.ArgumentParser(description="Export Jal Drishti flood risk report")
    parser.add_argument("--village", type=str, default="wayanad_meppadi")
    parser.add_argument("--rainfall", type=float, default=200.0)
    parser.add_argument("--output", type=str, default="output/reports")
    args = parser.parse_args()

    export_report(args.village, args.rainfall, args.output)


if __name__ == "__main__":
    main()
